version: "3.3"

services:
  mongo:
      container_name: mongo
      image: mongo:my-mongo-app
      build:
        context: ./
        dockerfile: mongo.dockerfile
      restart: on-failure:10
      volumes:
        - ./mongoDb/data:/data/db
      ports:
        - 27117:27017
  app:
    container_name: express_aplication_server
    image: node:my-app
    build:
        context: ./
        dockerfile: app.dockerfile
    working_dir: /home/node/project
    command: bash -c "npm i && cd ./log-viewer-gui && npm i && npm run build && cd .. && node app.js"
    depends_on:
      - mongo
    ports:
      - 8080:3000
